const teams=[
    {
        nome:'Juventus',
        puntiFatti:0,
        falliSubiti:0,     
    },
    {
        nome:'Inter',
        puntiFatti:0,
        falliSubiti:0,
    },
    {
        nome:'Milan',
        puntiFatti:0,
        falliSubiti:0,
    },
    {
        nome:'Roma',
        puntiFatti:0,
        falliSubiti:0,
    },
]